# Generated by Django 3.1.4 on 2021-01-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20210119_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
